#Requires -Version 5.1
# Varuna Windows agent installer (PoC). Runs as a normal user - no admin, no UAC.
# One-liner (generated by the Install Agent page):
#   $env:VARUNA_URL='https://host'; $env:VARUNA_TOKEN='<token>'; irm https://host/dist/install.ps1 | iex
$ErrorActionPreference = 'Stop'

if (-not $env:VARUNA_URL)   { throw 'VARUNA_URL not set. Copy the full command from the Install Agent page.' }
if (-not $env:VARUNA_TOKEN) { throw 'VARUNA_TOKEN not set. Copy the full command from the Install Agent page.' }
$BaseUrl = $env:VARUNA_URL.TrimEnd('/')
$Token   = $env:VARUNA_TOKEN

$Root = Join-Path $env:LOCALAPPDATA 'Varuna'
$Bin  = Join-Path $Root 'bin'
New-Item -ItemType Directory -Force -Path $Bin | Out-Null
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Write-Host "Installing Varuna agent into $Root ..."

# --- helper: download an asset from a GitHub release and SHA256-verify it ---
function Get-VerifiedRelease {
    param($Repo, $AssetMatch, $ChecksumMatch, $OutFile)
    $rel = Invoke-RestMethod "https://api.github.com/repos/$Repo/releases/latest" -Headers @{ 'User-Agent' = 'varuna-installer' }
    $asset = $rel.assets | Where-Object { $_.name -match $AssetMatch } | Select-Object -First 1
    $sums  = $rel.assets | Where-Object { $_.name -match $ChecksumMatch } | Select-Object -First 1
    if (-not $asset) { throw "No asset matching '$AssetMatch' in $Repo $($rel.tag_name)" }
    Invoke-WebRequest $asset.browser_download_url -OutFile $OutFile -UseBasicParsing
    if ($sums) {
        $sumsFile = "$OutFile.sums"
        Invoke-WebRequest $sums.browser_download_url -OutFile $sumsFile -UseBasicParsing
        $want = (Select-String -Path $sumsFile -Pattern ([regex]::Escape($asset.name)) | Select-Object -First 1).Line -replace '\s.*',''
        $have = (Get-FileHash $OutFile -Algorithm SHA256).Hash.ToLower()
        if (-not $want) { throw "Checksum for $($asset.name) not found in $($sums.name)" }
        if ($have -ne $want.ToLower()) { throw "SHA256 mismatch for $($asset.name): got $have want $want" }
    } else {
        throw "No checksums asset (match '$ChecksumMatch') in $Repo $($rel.tag_name); refusing unverified binary."
    }
    return $rel.tag_name
}

$versions = @{}

# --- 1. uv (provisions Python, no admin) ---
$uvZip = Join-Path $Root 'uv.zip'
$versions['uv'] = Get-VerifiedRelease 'astral-sh/uv' 'uv-x86_64-pc-windows-msvc\.zip$' '(sha256|SHA256SUMS|\.sha256)' $uvZip
Expand-Archive -Path $uvZip -DestinationPath $Bin -Force
$Uv = Join-Path $Bin 'uv.exe'
if (-not (Test-Path $Uv)) { $Uv = (Get-ChildItem $Bin -Recurse -Filter uv.exe | Select-Object -First 1).FullName }

# --- 2. Python venv + pip deps (httpx, python-dotenv, sqlmap) ---
$Venv = Join-Path $Root '.venv'
& $Uv venv --python 3.12 $Venv
$env:VIRTUAL_ENV = $Venv
& $Uv pip install --python (Join-Path $Venv 'Scripts\python.exe') httpx python-dotenv sqlmap
$versions['python'] = (& (Join-Path $Venv 'Scripts\python.exe') --version)

# --- 3. nuclei + katana (external Go binaries, verified) ---
$nucZip = Join-Path $Root 'nuclei.zip'
$versions['nuclei'] = Get-VerifiedRelease 'projectdiscovery/nuclei' 'windows_amd64\.zip$' 'checksums' $nucZip
Expand-Archive -Path $nucZip -DestinationPath $Bin -Force
$katZip = Join-Path $Root 'katana.zip'
$versions['katana'] = Get-VerifiedRelease 'projectdiscovery/katana' 'windows_amd64\.zip$' 'checksums' $katZip
Expand-Archive -Path $katZip -DestinationPath $Bin -Force

# --- 4. agent code from the control plane ---
$agentZip = Join-Path $Root 'agent-bundle.zip'
Invoke-WebRequest "$BaseUrl/dist/agent-bundle.zip" -OutFile $agentZip -UseBasicParsing
Expand-Archive -Path $agentZip -DestinationPath $Root -Force

# --- 5. launch shim: PATH so scan.py's bare nuclei/katana/sqlmap resolve; self-restart loop
#        keeps the agent up after a crash/network blip (mechanism-independent resilience) ---
$runShim = Join-Path $Root 'run-agent.ps1'
@"
`$env:VARUNA_URL = '$BaseUrl'
`$env:PATH = '$Bin;$(Join-Path $Venv 'Scripts');' + `$env:PATH
while (`$true) {
  & '$(Join-Path $Venv 'Scripts\python.exe')' '$(Join-Path $Root 'agent.py')'
  Start-Sleep -Seconds 5
}
"@ | Set-Content -Path $runShim -Encoding UTF8

# --- 6. enroll once and EXIT (--enroll: no poll loop here; the task below does the polling) ---
$env:VARUNA_URL = $BaseUrl
$env:PATH = "$Bin;$(Join-Path $Venv 'Scripts');$env:PATH"
& (Join-Path $Venv 'Scripts\python.exe') (Join-Path $Root 'agent.py') --enroll $Token

# --- 7. autostart at logon via the per-user Run key. This needs NO admin/UAC, unlike a
#        Scheduled Task in the root folder (denied to standard users -> 0x80070005). The
#        shim's own loop (step 5) provides the restart-on-crash that a task would give. ---
$launch = "powershell.exe -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$runShim`""
New-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run' `
    -Name 'VarunaAgent' -Value $launch -PropertyType String -Force | Out-Null
# start it now (don't wait for the next logon)
Start-Process -WindowStyle Hidden powershell.exe `
    -ArgumentList '-NoProfile','-WindowStyle','Hidden','-ExecutionPolicy','Bypass','-File',"`"$runShim`""

# --- record resolved versions for debugging/reproducibility ---
$versions.GetEnumerator() | ForEach-Object { "$($_.Key)=$($_.Value)" } | Set-Content (Join-Path $Root 'versions.txt')

Write-Host ''
Write-Host 'Varuna agent installed and running. It starts automatically at logon.'
Write-Host 'Go back to the Install Agent page and click refresh; status should show registered - online.'
